version: '2'
services:

  jenkins:
    build: ../jenkins/kubernetes
    networks:
      - jenkins
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
