#!/usr/bin/env groovy

library(
  identifier: 'shared-pipeline-from-external@1.0.0', // repository name shared pipeline // tag must be specified
  retriever: modernSCM(
    [
      $class: 'GitSCMSource',
      remote: 'https://github.com/jnjam6681/jenkins-cheat-sheet.git', // remote to url shared pipeline
      credentialsId: 'optional for auth'
    ]
  )
)

simplePipeline { // name of groovy file to use all function inside
  appName = 'app-service'
}   