version: '2'
services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: library/nginx:alpine
    restart: unless-stopped
    networks:
      - jenkins
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
    ports:
      - "80:80"
      - "443:443"

networks:
  jenkins:
